server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RPantaX/config-server-braidsbeautyByAngie
          clone-on-start: true
        default-label: main
  application:
    name: config-service

